# Exercises in numpy

In [1]:
import numpy as np

### Exercise 1

Create a numpy array of 8 rows and 4 columns which takes samples from the standard normal distribution. Call it data

In [2]:
data = np.random.randn(8,3)

### Exercise 2

Multiply each element of data by itself

In [3]:
data * data

array([[0.20234508, 7.88828353, 0.02038147],
       [4.26051136, 0.01136202, 0.13032194],
       [3.00401586, 0.9432984 , 0.45683147],
       [3.82063421, 6.34826404, 0.02934076],
       [0.67937996, 0.11567693, 0.43565296],
       [0.03353334, 0.20308937, 0.03867607],
       [1.36962411, 0.05922126, 0.57538311],
       [0.24502614, 1.88198538, 0.03374193]])

### Exercise 3

Create a ndarray from first 1000 integers. The array can be of any shape

In [7]:
x = np.arange(1000)

### Exercise 4

Create a ndarray of shape (8,4)  of zeros

In [8]:
a = np.zeros((8,4))

### Exercise 5

Create two random ndarrays of shape (6,2) called arr and arr2. Create a boolean array arr3 where arr3 = arr > arr2

In [10]:
arr = np.random.randn(6,2)
arr2 = np.random.randn(6,2)
arr > arr2

array([[ True, False],
       [ True, False],
       [ True,  True],
       [ True, False],
       [False,  True],
       [False,  True]])

### Exercise 6

From ex 5, use np.where to pick elements from arr if arr > arr2 else pick elements from arr2

In [11]:
np.where(arr > arr2, arr, arr2)

array([[-0.26175724,  1.06966676],
       [ 1.04798689,  1.41724759],
       [ 0.60813774,  0.48281068],
       [-0.60422745,  1.56400128],
       [ 0.68468417,  0.77350185],
       [-0.24258911, -0.20030693]])

### Exercise 7

Let a = np.arange(10)

(a) Print second element of a. There is zero based indexing<br>
(b) Print elements 2 to 5<br>
(c) Print last element<br>
(d) Print second last element<br>
(e) Assign 999 to elemtns 5 to 8<br>

In [14]:
### Your code here
a = np.arange(10)
print(a[1]) # (a)
print(a[2:5]) # (b)
print(a[-1]) # (c)
print(a[-2]) # (d)
a[4:7] = 999
print(a[4:7])

1
[2 3 4]
9
8
[999 999 999]


### Exercise 8

Create an array of shape (8,7). Call it data <br>

There is zero base indexing
(a) Print the element (4,4) <br>
(b) Print all rows and 1st column <br>
(c) Print 2nd row and all columns <br>
(d) Print 2nd row onwards and 3rd col onwards <br>
(e) Print upto 3rd row and upto 5th col <br>

In [16]:
### Your code here
data = np.random.randn(8,7)
print(data[4,4])
print(data[:,0])
print(data[1,:])
print(data[1:, 2:])
print(data[:2, :5])

-0.8034522284936155
[ 0.22053089 -1.02699131 -0.88228436 -0.76980817 -0.73955532 -0.29503812
  0.04398879  0.21184288]
[-1.02699131  0.34560187  0.49801496 -0.26323538  0.59358642  0.1985029
 -0.79094302]
[[ 0.49801496 -0.26323538  0.59358642  0.1985029  -0.79094302]
 [ 0.28469716  0.71175928  0.03713838  0.66741085 -1.08870951]
 [ 0.51278451  0.10454816  2.29240131  0.88091146 -0.38523503]
 [-0.01802114  0.9875642  -0.80345223  2.72548097  0.45955082]
 [-0.37700918  0.03608339  0.0864277   1.31060113 -0.31507528]
 [ 0.1150933   0.55139205  1.25125311  0.11675944 -0.78310794]
 [ 0.97862059 -0.0471019   0.82830956 -0.2764588  -1.89122534]]
[[ 0.22053089 -0.00972734 -0.11278078  0.3242131   0.05398462]
 [-1.02699131  0.34560187  0.49801496 -0.26323538  0.59358642]]


### Exercise 9

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])<br>
Print elements of array from ex 8 where index is names == 'Joe'<br>

In [18]:
### Your code here
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(data[:,names == 'Joe'])

[[-0.00972734  1.14920239 -0.82779933]
 [ 0.34560187  0.1985029  -0.79094302]
 [ 0.49545711  0.66741085 -1.08870951]
 [-1.45597247  0.88091146 -0.38523503]
 [-0.06051357  2.72548097  0.45955082]
 [ 0.49641004  1.31060113 -0.31507528]
 [-0.24681095  0.11675944 -0.78310794]
 [ 1.62380854 -0.2764588  -1.89122534]]


### Exercise 10

(a) Print all elements of data where data < 0 <br>
(b) Print all elements of data where data > 0 <br>

In [19]:
### Your code here
print(data[data < 0])
print(data[data > 0])

[-0.00972734 -0.11278078 -0.82779933 -1.02699131 -0.26323538 -0.79094302
 -0.88228436 -1.08870951 -0.76980817 -1.45597247 -0.38523503 -0.73955532
 -0.06051357 -0.01802114 -0.80345223 -0.29503812 -0.37700918 -0.31507528
 -0.24681095 -0.78310794 -0.0471019  -0.2764588  -1.89122534]
[0.22053089 0.3242131  0.05398462 1.14920239 0.34560187 0.49801496
 0.59358642 0.1985029  0.49545711 0.28469716 0.71175928 0.03713838
 0.66741085 0.51278451 0.10454816 2.29240131 0.88091146 0.9875642
 2.72548097 0.45955082 0.49641004 0.03608339 0.0864277  1.31060113
 0.04398879 0.1150933  0.55139205 1.25125311 0.11675944 0.21184288
 1.62380854 0.97862059 0.82830956]


### Exercise 11

Print elements (1,0), (5,3), (6,1), (2,2) of data in a single command

In [20]:
### Your code here
data[[1,5,6,1], [0,3,1,2]]

array([-1.02699131,  0.03608339, -0.24681095,  0.49801496])

### Exercise 12 

Create an array of shape (2,3,4) from first 24 integers

(a) transpose the axes, so axis 1, axis 0, axis 2 of arr means shape is (3,2,4)
(b) swap axes 1 and 2

In [24]:
### your code here
data = np.arange(24).reshape(2,3,4)
a = data.transpose(1,0,2)
b = data.swapaxes(1,2)

### Exercise 13

(a) Using np.linspace create 1000 points between -5 and 5 <br>
(b) Using np.arange create 1000 equally spaced points between -5 and 5

In [26]:
### Your code here
np.linspace(-5,5,1000)
np.arange(-5,5,0.01)

### Exercise 14

Create a random numpy array of shape (5,4)

(a) Calculate the mean of the array along the column axis, axis=1 <br>
(b) Calculate the cumulative sum along the row axis

In [27]:
### Your code here
data = np.random.randn(5,4)
data.mean(axis=1)
data.cumsum(axis=0)

array([[-2.29798472e-01, -1.02979082e+00,  2.13347259e-03,
        -2.32452541e-01],
       [-6.40598106e-02, -8.19623933e-02, -6.02925595e-01,
         9.96270622e-03],
       [-4.79019522e-02, -2.36525826e+00, -1.15624249e+00,
        -2.69027860e+00],
       [ 1.82465843e+00, -1.76787382e+00, -2.90114301e-01,
        -1.46468248e+00],
       [ 6.83535055e-01, -7.55046163e-01, -3.04238581e-01,
        -1.97925791e+00]])

### Exercise 15

(a) For the array in ex 14, find number of elements > 0 in a single command <br>
(b) Save the numpy array to disk <br>
(c) Load the numpy array from disk <br>
(d) Expand the array in ex 14 to 3 dimensions. You can place the extra axis anywhere.
(e) Broadcasting: Add np.array([1,-2, 3, 5]) to each of the columns

In [29]:
### Your code here
print((data > 0).sum())
np.save('../cache/a', a)

data = data + np.array([1,-2,3,5])

10
